//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH_Project.Data
{
    using System;
    using System.Collections.Generic;

    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.DonDatHangs = new HashSet<DONDATHANG>();
        }

        public int MaKH { get; set; } // PRIMARY KEY và IDENTITY
        public string HoTen { get; set; } // NOT NULL
        public string TaiKhoan { get; set; } // UNIQUE
        public string MatKhau { get; set; } // NOT NULL
        public string Email { get; set; } // UNIQUE
        public string DiaChiKH { get; set; } // Có thể NULL
        public string DienThoaiKH { get; set; } // Có thể NULL
        public DateTime? NgaySinh { get; set; } // Có thể NULL

        public virtual ICollection<DONDATHANG> DonDatHangs { get; set; } // Quan hệ với DONDATHANG
    }
}
